using System;
using System.Collections.Generic;

#nullable disable

namespace POS_API.Models
{
    public partial class ItemInfoView
    {
        public int ItmSerial { get; set; }
        public string ItmCode { get; set; }
        public string ItemNameL1 { get; set; }
        public string ItemNameL2 { get; set; }
        public string DescriptionInSales { get; set; }
        public string DescriptionInPurchase { get; set; }
        public string GroupCode { get; set; }
        public string GroupNameL1 { get; set; }
        public string GroupNameL2 { get; set; }
        public int GroupColor { get; set; }
        public int? CategoryId { get; set; }
        public string CategoryNameL1 { get; set; }
        public int CategoryColor { get; set; }
        public int CategoryOrderNo { get; set; }
        public string CategoryNameL2 { get; set; }
        public string PurchaseUnitCode { get; set; }
        public string PurchaseUnitNameL1 { get; set; }
        public string PurchaseUnitNameL2 { get; set; }
        public string LargUnitCode { get; set; }
        public string LargeUnitNameL1 { get; set; }
        public string LargeUnitNameL2 { get; set; }
        public string MedUnitCode { get; set; }
        public string MediumUnitNameL1 { get; set; }
        public string MediumUnitNameL2 { get; set; }
        public string SalesUnitCode { get; set; }
        public string SalesUnitNameL1 { get; set; }
        public string SalesUnitNameL2 { get; set; }
        public double? FactorPurchaseToSmall { get; set; }
        public double? FactorLargToMed { get; set; }
        public double? FactorLargToSmall { get; set; }
        public double? FactorMedToSmall { get; set; }
        public string Picture { get; set; }
        public int? QuickFlag { get; set; }
        public DateTime? LastSalesDate { get; set; }
        public decimal? LastSalesPrice { get; set; }
        public decimal? OfferDefaultPrice { get; set; }
        public decimal? PriceListDefaultPrice { get; set; }
        public DateTime? LastPurchaseDate { get; set; }
        public decimal? LastPurchasePrice { get; set; }
        public double? MinQty { get; set; }
        public double? MaxQty { get; set; }
        public double? ReorderQty { get; set; }
        public int? SerialId { get; set; }
        public int? IsWeightFlag { get; set; }
        public int? Status { get; set; }
        public string ItmStatusDesc { get; set; }
        public int? AllowSales { get; set; }
        public string AllowSalesDesc { get; set; }
        public int? AllowPurchase { get; set; }
        public string AllowPurchaseDesc { get; set; }
        public int? AllowReturn { get; set; }
        public string AllowReturnDesc { get; set; }
        public int? UseAddOns { get; set; }
        public string UseAddOnsDesc { get; set; }
        public int? UseExpiry { get; set; }
        public string UseExpiryDesc { get; set; }
        public int? ShowButtonInSales { get; set; }
        public string ShowButtonInSalesDesc { get; set; }
        public int? AllowEditPrice { get; set; }
        public string AllowEditPriceDesc { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeCodeDesc { get; set; }
        public int? ItemNature { get; set; }
        public string ItemNatureDesc { get; set; }
        public decimal AverageCost { get; set; }
        public decimal LandedCost { get; set; }
        public decimal CompanyCurrentBalance { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal Discount { get; set; }
        public decimal SalesTaxPercent { get; set; }
        public decimal SalesTaxAmount { get; set; }
        public decimal PurchaseTaxPercent { get; set; }
        public decimal PurchaseTaxAmount { get; set; }
        public string ItmCode1 { get; set; }
        public string ItmCode2 { get; set; }
        public string ItmCode3 { get; set; }
        public string ItmCode4 { get; set; }
        public string ItmCode5 { get; set; }
        public string ItmCode6 { get; set; }
        public string ItmCode7 { get; set; }
        public string ItmCode8 { get; set; }
        public string ItmCode9 { get; set; }
        public string ItmCode10 { get; set; }
        public string ItmCode11 { get; set; }
        public string ItmCode12 { get; set; }
        public string ItmCode13 { get; set; }
        public string ItmCode14 { get; set; }
        public string ItmCode15 { get; set; }
        public string ItmCode16 { get; set; }
        public string ItmCode17 { get; set; }
        public string ItmCode18 { get; set; }
        public string ItmCode19 { get; set; }
        public string ItmCode20 { get; set; }
        public string ItmIsCat { get; set; }
        public int? ItmCatMixNo { get; set; }
        public string ItmPricingType { get; set; }
        public string ItmPricingTypeDesc { get; set; }
        public decimal? ItmMarkup { get; set; }
        public decimal? ItmProfit { get; set; }
        public int? ModelId { get; set; }
        public string ModelCode { get; set; }
        public string ModelDescription { get; set; }
        public string XAttributeValue { get; set; }
        public string YAttributeValue { get; set; }
        public int? PreferedVendor { get; set; }
        public string VendorName { get; set; }
        public string DefaultSalesUnit { get; set; }
        public string DefaultSalesUnitCode { get; set; }
        public string DefaultSalesUnitNameL1 { get; set; }
        public string DefaultSalesUnitNameL2 { get; set; }
        public string MajorTime { get; set; }
        public string ExpireDate { get; set; }
        public int? UseLinkedItems { get; set; }
        public string UseLinkedItemsDesc { get; set; }
        public int? AllowChangeName { get; set; }
        public string AllowChangeNameDesc { get; set; }
        public int? UseSerialNo { get; set; }
        public string UseSerialNoDesc { get; set; }
        public DateTime LastUpdate { get; set; }
        public string UserId { get; set; }
        public int? KitchenId { get; set; }
        public string KitchenName { get; set; }
        public string KitchenPrinterName { get; set; }
    }
}
